version: '3.8'

services:
  graph-db:
    image: neo4j:latest
    ports:
      - "7474:7474"   # HTTP
      - "7687:7687"   # BOLT
    environment:
      NEO4J_AUTH: neo4j/password  # Replace with your desired username and password

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - graph-db